version: '3.6'

services:
  crop_yaml_blender:
    container_name: crop_yaml_blender 
    build:
      context: ./cropcraft
      dockerfile: crop.dockerfile
    volumes:
      - ./src:/app/src
  ros:
    container_name: ros_aloam
    build:
      context: ./ros
      dockerfile: ros.dockerfile
    volumes: 
      - ./src:/root/catkin_ws/src/

