version: '3.8'

services:
  blender:
    build:
      context: ./blender
      dockerfile: Dockerfile.blender
    container_name: blender_cropcraft 
    # security_opt:
    #   - seccomp:unconfined #optional
    environment: 
      - PUID=1000 # 
      - PGID=1000 # 
      - TZ=America/Sao_Paulo # Time Zone
      # - SUBFOLDER=/ #optional
    networks:
      - blender_net
    volumes:
      - ./blender/src/config:/config
      - ./blender/cropcraft:/cropcraft
      - blender_data:/cropcraft/src/gazebo
    restart: unless-stopped 

  ros:
    build:
      context: ./ros/weed_robot_simulation-master
      dockerfile: Dockerfile.ros
    container_name: ros
    networks:
      - blender_net
    depends_on:
      - blender
    environment:
      - PYTHON_HOST=blender
    volumes: 
      - ./ros/src:/root/catkin_ws/src/
      - blender_data:./src/gazebo_blender
networks:
  blender_net:
    driver: bridge
